name: Test Full Stack Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies (root)
      run: npm install

    - name: Install Supabase CLI
      run: |
        npm install -g @supabase/cli
        supabase --version

    - name: Install frontend dependencies
      run: |
        cd apps/frontend
        npm install

    - name: Install Playwright Browsers
      run: |
        cd apps/frontend
        npx playwright install --with-deps

    - name: Start Supabase local development
      run: |
        supabase start --exclude=edge-runtime,studio,storage-api,imgproxy,inbucket
      env:
        SUPABASE_DB_PORT: 5432

    - name: Run database migrations and seed
      run: |
        supabase db reset --linked=false

    - name: Build Angular application
      run: |
        cd apps/frontend
        npm run build

    - name: Run Playwright tests
      run: |
        cd apps/frontend
        npm run e2e
      env:
        CI: true

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: apps/frontend/playwright-report/
        retention-days: 30
        
    - name: Stop Supabase
      run: supabase stop
      if: always()